server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
okta:
  oauth2:
    redirectUri: /authorization-code/callback

security:
  oauth2:
    client:
      # Redirect to your local page and render the widget
      userAuthorizationUri: http://localhost:${server.port}/login