/*!
 * Copyright (c) 2015-2016, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */
/* eslint-disable */

/* --- This file was auto-generated by generate-keys.js --- */
module.exports = {
  privatePem: `-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEArma0PJ91FQXbQTRKKrVxx3DqP8QGyf1xBx7c2mtlv6jvPSv/
+QvLTQO0dP86eQNzgSQPZlYhja5JC+MkwC2ncSGxkGJ+2jaJUlDd4wDopr5PX5RQ
ZKiQ1mJWDGmHgO9nhVFXce5gGp22YcDQYfUHN/1gHFJYxqIHE62Dnr2mRXUCmmGJ
6l19PAKb+S5aqdXvYpYgXAwMIt2Tb6PcBynHBOp/fHbqCRb8uUdJTfGYPgExTsC8
04qAmbEE9G9M2L6XKo3ADH7kIcvZRof2l8y8X6QX9sKTqdRWRYvnmpcaKlbM3JKS
dZlLSHzL1rghn8W12wR0KZbLTtu8o762AHnFFwIDAQABAoIBABlOofziDrVcQjK2
CcUkyzvrsLJMGcgZ1Nr5qYawavVi6ERyLBTRl1C3puoLV0rUK2CkAPASs4/BqKvm
7CBO/6s0/nU7NbkojMi7H1effCMmHpJ6DShuJYZWgrIOZjFZjCYWZaAMvTlfhWWt
+w8b5U5EoDu731IDlQ9P8HeKgaQ2VvcpzLLmpHkJHYNe3l/QN7PjceAHuWtcCtIQ
oRBpa7jsGMLJ78ABL1SYS2klBT5x6/m8FTMicgqTVh8cWcLLThhXvg8MUrEQ0JHX
YGOcLL9eoDCCG+fFoGCoN/uihzYKFTIYbRPiWMVqEadFNpluTOOtyoN4j9eFOHk9
1l+7MlECgYEA5wCZCs7oPUjFcNkjJimP7TQqMDm6nROrq7y4FUQjg7nejG7WV1CA
OHhaTYf8n6VWX1qm3wPJN6yisgLJpxzWJ60+Y0rCB0xJ+8e7t7si2c6jSlGiXiQU
PGnutoA4E8Nv4abtd96IePvMRAKlhZJqol9O2OMN9u31WMEZQVg+NsMCgYEAwUYZ
Jk820IOXAmkXfK33T2+keW9szGKojy+tuX1YTvd+r9bos54hGDFuMdd/G+2zNSHq
aPM+bT080kJIpUXCL8E0RV6qWW6HQkMzVtjhOI7d0gd63Ho93NoJY5toQyt72v/e
8r3YOFRCFHih4E0u+V9RhDLoknp/j0QxSJNNGx0CgYA1FFMWQ7LjmhwcMRi9hSFY
PPtQt4Mk4sc4oBWgdVa/xu7XUASabZn439bIJ+4pdOFi6b6cUg9jZpy/0JordxnS
ZiGGyT/KU4JQg3Wj4zE/4RZuVlG71gh8VU8PymiYSfkkXaoFODIdsqYeHomQJrOv
+bxxY8LqsYUFzuERvcgV5wKBgGo6khYpUdJ3kSeFBaDEqXqivT71jFImI8lXhl++
UixNAfe54nre/gejG5MPg9Cg7G/WrVVz5Kr8DpLuValpVxsSUR2Ts4OmKXe1IeGp
INkKRUdsTw4hriDWQnTZ9Qt+OfwbyLmYuN/1B8DisO5s3dW4m0BTDtt7suLWs1PV
inrNAoGBAN2w3kRQ9l8hEvx6kzDAmagEEgxOTrpF4BGYtI7nMEpDP/4F+BBp1/u/
Ao/5nW1g/BNKNmfyDAoZVuDB7GmYGhml9NxFZqIS6DHuA10hIca86SzP7GVWiT9A
tQpTQDyysEa4e3GEBDPClxgrKOqOIUmS+rLx5FCev7RHRHrlUUUe
-----END RSA PRIVATE KEY-----
`,
  publicPem: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArma0PJ91FQXbQTRKKrVx
x3DqP8QGyf1xBx7c2mtlv6jvPSv/+QvLTQO0dP86eQNzgSQPZlYhja5JC+MkwC2n
cSGxkGJ+2jaJUlDd4wDopr5PX5RQZKiQ1mJWDGmHgO9nhVFXce5gGp22YcDQYfUH
N/1gHFJYxqIHE62Dnr2mRXUCmmGJ6l19PAKb+S5aqdXvYpYgXAwMIt2Tb6PcBynH
BOp/fHbqCRb8uUdJTfGYPgExTsC804qAmbEE9G9M2L6XKo3ADH7kIcvZRof2l8y8
X6QX9sKTqdRWRYvnmpcaKlbM3JKSdZlLSHzL1rghn8W12wR0KZbLTtu8o762AHnF
FwIDAQAB
-----END PUBLIC KEY-----
`,
  publicJwk: {"kty":"RSA","n":"rma0PJ91FQXbQTRKKrVxx3DqP8QGyf1xBx7c2mtlv6jvPSv_-QvLTQO0dP86eQNzgSQPZlYhja5JC-MkwC2ncSGxkGJ-2jaJUlDd4wDopr5PX5RQZKiQ1mJWDGmHgO9nhVFXce5gGp22YcDQYfUHN_1gHFJYxqIHE62Dnr2mRXUCmmGJ6l19PAKb-S5aqdXvYpYgXAwMIt2Tb6PcBynHBOp_fHbqCRb8uUdJTfGYPgExTsC804qAmbEE9G9M2L6XKo3ADH7kIcvZRof2l8y8X6QX9sKTqdRWRYvnmpcaKlbM3JKSdZlLSHzL1rghn8W12wR0KZbLTtu8o762AHnFFw","e":"AQAB","alg":"RS256","use":"sig","kid":"TEST_KID_1"}
};
