/*!
 * Copyright (c) 2015-2016, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */
/* eslint-disable */

/* --- This file was auto-generated by generate-keys.js --- */
module.exports = {
  privatePem: `-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA93kOBi8jdDvCSH8z1FbUOPTXe8qjMfbhDcdBRW4Vev4b19RV
DX4Nq9goKI60T09nGe1JqUO3SeJtNqv2eQ3TP7eHx7ydX8Rc7MvTFc1KHIpIi7bN
2v1kr92QqMhCh4D4+edX6PCTsGsL0gGE/2lWPQE8IhOByXKioZB/o9hDBAiB0fzQ
yKhusu1/+yc6jAfXy4A8aQ8zON7jLLWxRaaDgVHNp0MYj9e5qaP64HRPS8Ong3KA
yb25wriw/EyraRDLgIYCNFwsEiYSk1X/ijzLk3S6Pn3KZ5itf1cdn7EaiZp6Q/2w
Lenx92za/YQlMIQpb85S6eGaKrpjPEPd4Xaw/QIDAQABAoIBAQC2glu6adde6Jef
OdiymBrJqqCk1kxHFAjkTXgwyUAkRfWo1hqn6bgRbUgoqR4Hg8rIzzxNDfjGD6x1
7prGqlCKpEMKJmt17m6N4MBbStyGceGQ0I+/GrPAE8qU/6Q5JP/55gjqbUquiDPe
fGpmp3wHX7rGctZ8CAQy3UuVPXAnLt+smc2IeGg/O4vEWKtX4Us7MgztDquX7pov
FVyidzXI19aGAnZNBACasc97GdVUl74URd2Sy/38gH+Pj8ASa+p81jWo7P7jcJsw
XpToGbWkXm7Yt3IGLAr5zmipeJPVQbAbqhMUna2tVT3kqYfOjKAJlcYgAE2GUGwG
/gfa+ArBAoGBAP8KMtU3OHIbvWLaRt56gGgRF9PpVf0UcRihDuxzjCibxjTNYfEp
+FGq2aZXdxFpSLtIScOOMfTNdVRL0I/N8ZXhNaGtAq49dfYVcJN5GLHxFktUDR39
+b0DWCJ+BbzbhVal2AdWZHobclUq//ukOPlzne1R6Zq542zSrGLotqXtAoGBAPhn
kDemssHI0shYtJccp1/QinGEuGXNmHcWvgRdY14BZu1GMzpqW3cF9wxirWYP9ipg
OZakuP4nPpWO/M5oQkNEhCNTbyqIy7lwvveqX5Ou4Qe0ptfTUF0c5idExMRKrGcH
5zK+2Ih1b+TZU08zd7Z24VYSDYaRwh5g2h9yVtVRAoGBAIBF3t9CUM+DiDNp2W8Y
afDtd/CLUUZiu6dJijn+u6XJA12XVwV2uIBK0AFLyIUnUP9xEjibEiEwHSzynMlX
KYTaqqDQZaLBIs1MZzylEXid6zqj4Z0OGkeooPFoNPaR6nR0IT0/hHWtzEltwSYN
qOI99lZgdn/tsqcPJsjwhrzZAoGAV6GxbvCP/20pbyRcETM6mMKpFIMNylxNfTW4
szF+7JryBKLPT7xVqBein+vv4CGhZjGsH0jdOkv9+CUJaoe9WJ3DP/MfNJItzK3J
sPWZ4i+/k0hX06vonfCkARZxlA4D5BUVqwFIwlsrrkA886Pkh6pItGSKAP9KzAy+
5nkfyQECgYBQS3/ZJsWWfSa5e88vmJFE1lcUmsZXrSlmoag6vHy7dgIsTYCa07KK
pLcAWd1lNt8i4bI0tH7f4s/Z460XSc5FgolRTixU3xl7qUHulGpVdInonEIMla72
qvqdFTfWYQqYR+5CIYMzjLd9xLm6yqjO49KleFiGjpxiY8pzllve3Q==
-----END RSA PRIVATE KEY-----
`,
  publicPem: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA93kOBi8jdDvCSH8z1FbU
OPTXe8qjMfbhDcdBRW4Vev4b19RVDX4Nq9goKI60T09nGe1JqUO3SeJtNqv2eQ3T
P7eHx7ydX8Rc7MvTFc1KHIpIi7bN2v1kr92QqMhCh4D4+edX6PCTsGsL0gGE/2lW
PQE8IhOByXKioZB/o9hDBAiB0fzQyKhusu1/+yc6jAfXy4A8aQ8zON7jLLWxRaaD
gVHNp0MYj9e5qaP64HRPS8Ong3KAyb25wriw/EyraRDLgIYCNFwsEiYSk1X/ijzL
k3S6Pn3KZ5itf1cdn7EaiZp6Q/2wLenx92za/YQlMIQpb85S6eGaKrpjPEPd4Xaw
/QIDAQAB
-----END PUBLIC KEY-----
`,
  publicJwk: {"kty":"RSA","n":"93kOBi8jdDvCSH8z1FbUOPTXe8qjMfbhDcdBRW4Vev4b19RVDX4Nq9goKI60T09nGe1JqUO3SeJtNqv2eQ3TP7eHx7ydX8Rc7MvTFc1KHIpIi7bN2v1kr92QqMhCh4D4-edX6PCTsGsL0gGE_2lWPQE8IhOByXKioZB_o9hDBAiB0fzQyKhusu1_-yc6jAfXy4A8aQ8zON7jLLWxRaaDgVHNp0MYj9e5qaP64HRPS8Ong3KAyb25wriw_EyraRDLgIYCNFwsEiYSk1X_ijzLk3S6Pn3KZ5itf1cdn7EaiZp6Q_2wLenx92za_YQlMIQpb85S6eGaKrpjPEPd4Xaw_Q","e":"AQAB","alg":"RS256","use":"sig","kid":"TEST_KID_2"}
};
